package modal;
// Generated Feb 27, 2018 1:00:25 PM by Hibernate Tools 4.3.1



/**
 * BillDetail generated by hbm2java
 */
public class BillDetail  {

    public Integer getBillDetailId() {
        return billDetailId;
    }

    public void setBillDetailId(Integer billDetailId) {
        this.billDetailId = billDetailId;
    }

    public Bill getBill() {
        return bill;
    }

    public void setBill(Bill bill) {
        this.bill = bill;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public BillDetail(Integer billDetailId, Bill bill, Product product, double price, int quantity) {
        this.billDetailId = billDetailId;
        this.bill = bill;
        this.product = product;
        this.price = price;
        this.quantity = quantity;
    }

    public BillDetail() {
    }

    public BillDetail(Integer billDetailId, Product product, double price, int quantity) {
        this.billDetailId = billDetailId;
        this.product = product;
        this.price = price;
        this.quantity = quantity;
    }


     private Integer billDetailId;
     private Bill bill;
     private Product product;
     private double price;
     private int quantity;

 

}


