package modal;
// Generated Feb 27, 2018 1:00:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category   {

    public Integer getCategoryId() {
        return categoryId;
    }

    public Category(String categoryName) {
        this.categoryName = categoryName;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public Category(Integer categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }

    public Category() {
    }




     private Integer categoryId;
     private String categoryName;

    public Category(Integer categoryId) {
        this.categoryId = categoryId;
    }
    



}


