package modal;
// Generated Feb 27, 2018 1:00:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  {

    public Khachhang() {
    }

    public Khachhang(String fname, String lname, String fullname, boolean sex, String phone, String email, String adress) {
        this.fname = fname;
        this.lname = lname;
        this.fullname = fullname;
        this.sex = sex;
        this.phone = phone;
        this.email = email;
        this.adress = adress;
    }

    public Khachhang(Integer id, String fname, String lname, String fullname, boolean sex, String phone, String email, String adress) {
        this.id = id;
        this.fname = fname;
        this.lname = lname;
        this.fullname = fullname;
        this.sex = sex;
        this.phone = phone;
        this.email = email;
        this.adress = adress;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public boolean getSex() {
        return sex;
    }

    public void setSex(boolean sex) {
        this.sex = sex;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAdress() {
        return adress;
    }

    public void setAdress(String adress) {
        this.adress = adress;
    }


     private Integer id;

    public Khachhang(String fullname) {
        this.fullname = fullname;
    }
     private String fname;
     private String lname;
     private String fullname;
     private boolean sex;
     private String phone;
     private String email;
     private String adress;
    



}


